import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@/styles/thirdparty/normalize.css";
import "@/styles/globals.scss";
import "@/styles/dual-render.scss";

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
 
  // suppressHydrationWarning present because we manipulate the dataset on the
  // client.  Are we sure this is a legitimate software engineering field?
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{
          __html:
            `
            const stored = localStorage.getItem("theme");
            const preference =
              stored === "light" ||
              stored === "dark" ||
              stored === "system"
                ? stored
                : "system";
            
            const systemDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
            const resolved = preference === "system" ? (systemDark ? "dark" : "light") : preference;

            document.documentElement.dataset.theme = resolved;

            document.documentElement.dataset.js = "true";
            `
        }} />
      </head>

      <body>{children}</body>
    </html>
  );
}
