import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";

import "@/styles/globals.css";
import "@/styles/dual-render.css";

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
 
  // suppressHydrationWarning present because we manipulate the dataset on the
  // client.  Are we sure this is a legitimate software engineering field?
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script id="dual-render-bootstrap" strategy="beforeInteractive">
          {`document.documentElement.dataset.js = "true";`}
        </Script>
      </head>

      <body>{children}</body>
    </html>
  );
}
